export const projects = [
    {
        id: 1,
        title: "gymWebSite",
        liveDemo: "https://h-habka.github.io/gymWebSite",
        github: "https://github.com/H-Habka/gymWebSite",
        language: "React",
        image: "gymWebSite.webp",
        blurb: "Personal React gym website. Live demo and source as published.",
    },
    {
        id: 2,
        title: "youtube Clone",
        liveDemo: "https://h-habka.github.io/youtubeClone",
        github: "https://github.com/H-Habka/youtubeClone",
        language: "React",
        image: "youtubeClone.webp",
        blurb: "Personal React YouTube clone. Live demo and source as published.",
    },
    {
        id: 3,
        title: "crwn-clothing",
        liveDemo: "https://h-habka.github.io/crwn-clothing",
        github: "https://github.com/H-Habka/crwn-clothing",
        language: "React",
        image: "crown-clothing.webp",
        blurb: "Personal React clothing-store demo. Live demo and source as published.",
    },
    {
        id: 4,
        title: "Product-preview-card",
        liveDemo: "https://h-habka.github.io/Product-preview-card-components/",
        github: "https://github.com/H-Habka/Product-preview-card-components",
        language: "HTML+CSS",
        image: "Product-preview-card.webp",
        blurb: "Personal HTML and CSS product preview card. Live and source as published.",
    },
    {
        id: 5,
        title: "rockPaperScissors",
        liveDemo: "https://h-habka.github.io/rockPaperScissors/",
        github: "https://github.com/H-Habka/rockPaperScissors",
        language: "React",
        image: "rockPaperScissors.webp",
        blurb: "Personal React rock-paper-scissors demo. Live and source as published.",
    },
    {
        id: 6,
        title: "weather-App",
        liveDemo: "https://h-habka.github.io/weather-App/",
        github: "https://github.com/H-Habka/weather-App",
        language: "React",
        image: "weather-App.webp",
        blurb: "Personal React weather app. Live demo and source as published.",
    },
    {
        id: 7,
        title: "Interactive-card",
        liveDemo: "https://h-habka.github.io/Interactive-card-details-form/",
        github: "https://github.com/H-Habka/Interactive-card-details-form",
        language: "React",
        image: "Interactive-card.webp",
        blurb: "Personal React interactive card-details form. Live and source as published.",
    },
    {
        id: 8,
        title: "advice-generator",
        liveDemo: "https://h-habka.github.io/advice-generator-app/",
        github: "https://github.com/H-Habka/advice-generator-app",
        language: "HTML+CSS",
        image: "advice-generator.webp",
        blurb: "Personal HTML and CSS advice generator. Live and source as published.",
    },
    {
        id: 9,
        title: "monster-rolodex",
        liveDemo: "https://h-habka.github.io/monster-rolodex/",
        github: "https://github.com/H-Habka/monster-rolodex",
        language: "React",
        image: "monster-rolodex.webp",
        blurb: "Personal React monster rolodex. Live demo and source as published.",
    },
    {
        id: 10,
        title: "Tip-calculator-app",
        liveDemo: "https://h-habka.github.io/Tip-calculator-app/",
        github: "https://github.com/H-Habka/Tip-calculator-app",
        language: "React",
        image: "Tip-calculator-app.webp",
        blurb: "Personal React tip calculator. Live demo and source as published.",
    },
    {
        id: 11,
        title: "Expenses-chart",
        liveDemo: "https://h-habka.github.io/Expenses-chart-component/",
        github: "https://github.com/H-Habka/Expenses-chart-component",
        language: "HTML+CSS",
        image: "Expenses-chart.webp",
        blurb: "Personal HTML and CSS expenses chart. Live and source as published.",
    },
    {
        id: 12,
        title: "portfolio",
        liveDemo: "https://h-habka.github.io/myPortfolio/",
        github: "https://github.com/H-Habka/myPortfolio",
        language: "React",
        image: "portfolio.webp",
        blurb: "This site. Live demo and source as published.",
    },
];
